name: "airflow-stack"

services:
  postgresdb:
    image: postgres:17
    container_name: airflow-stack-postgres
    hostname: airflow-stack-postgres
    environment:
      POSTGRES_PASSWORD: postgres_P4ssw0rd!
    volumes:
      - ./airflow_db_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - airflow-postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

 
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-stack-airflow
    hostname: airflow-stack-airflow
    ports:
      - "8080:8080"
    volumes:
      - ../dags:/airflow/dags
      - ../logs:/airflow/logs
    depends_on:
      postgresdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

 

volumes:
  airflow-postgres:
    driver: local
  airflow-logs:
    driver: local